name: Deploy master
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: "12.19.x"
                  check-latest: true

            - name: Checkout source code
              uses: actions/checkout@v1

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install dependencies
              run: npm install

            - name: Build
              run: NODE_ENV=production BASE_URL=https://getmakerlog.com npm run build

            - name: Package the slug
              run: zip -r deploy.zip . -x ./node_modules/\*

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v10
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: unicorn
                  environment_name: unicorn-dev
                  version_label: ${{github.SHA}}
                  region: ${{ secrets.AWS_DEFAULT_REGION }}
                  use_existing_version_if_available: true
                  deployment_package: deploy.zip

            - uses: act10ns/slack@v1
              with:
                  status: ${{ job.status }}
                  steps: ${{ toJson(steps) }}
                  channel: "#ops"
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              if: always()
